[package]
name = "alarm-clock"
version = "0.1.0"
edition = "2021"

[dependencies]
esp-hal = { workspace = true }
esp-backtrace = { workspace = true }
esp-println = { workspace = true }
embassy-executor = { workspace = true }
embassy-time = { workspace = true }
esp-bootloader-esp-idf = { workspace = true }
esp-rtos = { workspace = true }
embassy-sync = { workspace = true }
bitmask-enum = "2.2.5"
embassy-futures = "0.1.2"
